export const ERC20_SYMBOL_TO_ICON: Record<string, string> = {
  usdc: '/images/erc20/usdc.png',
  pusdc: '/images/erc20/usdc.png',
  'usdc.e': '/images/erc20/usdc.png',
  usdbc: '/images/erc20/usdc.png',
  usdbcx: '/images/erc20/usdc.png',
  usdcx: '/images/erc20/usdc.png',
  xdai: '/images/erc20/dai.png',
  xdaix: '/images/erc20/dai.png',
  dai: '/images/erc20/dai.png',
  daix: '/images/erc20/dai.png',
  usdt: '/images/erc20/usdt.png',
  usdtx: '/images/erc20/usdtx.png',
  lusd: '/images/erc20/lusd.png',
  aave: '/images/erc20/aave.png',
  comp: '/images/erc20/aave.png',
  op: '/images/erc20/op.svg',
  opx: '/images/erc20/op.svg',
  eth: '/images/erc20/eth.svg',
  ethx: '/images/erc20/eth.svg',
  weth: '/images/erc20/weth.png',
  steth: '/images/erc20/steth.png',
  reth: '/images/erc20/reth.png',
  btc: '/images/erc20/btc.png',
  wbtc: '/images/erc20/btc.png',
  wbtcx: '/images/erc20/btc.png',
  susd: '/images/erc20/susd.png',
  sdai: '/images/erc20/sdai.png',
  frax: '/images/erc20/frax.png',
  gusd: '/images/erc20/gusd.png',
  uni: '/images/erc20/uni.png',
  usdp: '/images/erc20/usdp.webp',
  knc: '/images/erc20/knc.png',
  crvusd: '/images/erc20/crvUSD.svg',
  stg: '/images/erc20/stg.png',
  bal: '/images/erc20/bal.png',
  ldo: '/images/erc20/ldo.png',
  crv: '/images/erc20/crv.png',
  crvx: '/images/erc20/crv.png',
  fxs: '/images/erc20/fxs.png',
  fpi: '/images/erc20/fpi.png',
  '1inch': '/images/erc20/1inch.png',
  snx: '/images/erc20/snx.png',
  ens: '/images/erc20/ens.png',
  rpl: '/images/erc20/rpl.png',
  rplx: '/images/erc20/rpl.png',
  mkr: '/images/erc20/mkr.png',
  mkrx: '/images/erc20/mkr.png',
  link: '/images/erc20/link.png',
  linkx: '/images/erc20/link.png',
  gno: '/images/erc20/gno.png',
  eur: '/images/erc20/eur.svg',
  eurx: '/images/erc20/eur.svg',
  matic: '/images/erc20/matic.png',
  pol: '/images/erc20/matic.png',
  wmatic: '/images/erc20/matic.png',
  waticx: '/images/erc20/matic.png',
  maticx: '/images/erc20/maticx.webp',
  stmatic: '/images/erc20/stmatic.png',
  ghst: '/images/erc20/ghst.png',
  sushi: '/images/erc20/sushi.png',
  dpi: '/images/erc20/dpi.png',
  arb: '/images/erc20/arb.png',
  cvx: '/images/erc20/cvx.png',
  gohm: '/images/erc20/gohm.webp',
  gmx: '/images/erc20/gmx.webp',
  gem: '/images/erc20/gem.png',
  przusdc: '/images/erc20/przusdc.png',
  mwusdc: '/images/erc20/usdc.png',
  tybg: '/images/erc20/tybg.png',
};

export function getErc20Icon(symbol: string | null | undefined) {
  return (
    ERC20_SYMBOL_TO_ICON?.[symbol?.toLowerCase() || ''] ||
    '/images/erc20/unknown.png'
  );
}
