export const erc20BalanceGteWrapEnforcerAbi = [
  {
    type: 'function',
    name: 'afterAllHook',
    inputs: [
      { name: '_terms', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'ModeCode' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '_delegationHash', type: 'bytes32', internalType: 'bytes32' },
      { name: '_delegator', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'afterHook',
    inputs: [
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'ModeCode' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'bytes32' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceCache',
    inputs: [{ name: 'hashKey', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: 'balance', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'beforeAllHook',
    inputs: [
      { name: '_terms', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'ModeCode' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '_delegationHash', type: 'bytes32', internalType: 'bytes32' },
      { name: '_delegator', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'beforeHook',
    inputs: [
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'ModeCode' },
      { name: '', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'bytes32', internalType: 'bytes32' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getHashKey',
    inputs: [
      { name: '_caller', type: 'address', internalType: 'address' },
      { name: '_token', type: 'address', internalType: 'address' },
      { name: '_delegationHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'getTermsInfo',
    inputs: [{ name: '_terms', type: 'bytes', internalType: 'bytes' }],
    outputs: [
      { name: 'token_', type: 'address', internalType: 'address' },
      { name: 'amount_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'isLocked',
    inputs: [{ name: 'hashKey', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: 'lock', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'error',
    name: 'BalanceNotGreaterOrEqualThan',
    inputs: [
      { name: 'balance', type: 'uint256', internalType: 'uint256' },
      { name: 'expected', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { type: 'error', name: 'EnforcerIsLocked', inputs: [] },
  {
    type: 'error',
    name: 'InvalidTermsLength',
    inputs: [
      { name: 'length', type: 'uint256', internalType: 'uint256' },
      { name: 'expected', type: 'uint256', internalType: 'uint256' },
    ],
  },
] as const;
